version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    REPOSITORY_URI: "866945988845.dkr.ecr.us-east-1.amazonaws.com/brain-task-app"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - LOGIN_PASSWORD=$(aws ecr get-login-password --region $AWS_REGION)
      - docker login --username AWS --password "$LOGIN_PASSWORD" $REPOSITORY_URI
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - echo "Using image tag $IMAGE_TAG"

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Creating imageDetail.json...
      - echo "{\"imageUri\":\"$REPOSITORY_URI:$IMAGE_TAG\"}" > imageDetail.json
      - echo Build completed successfully.

artifacts:
  files:
    - imageDetail.json
    - k8s/deployment.yaml
    - k8s/service.yaml
    - deployspec.yml
    - appspec.yml
    - scripts/*
