apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: brain-task-app
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: brain-task-stable-service
      previewService: brain-task-preview-service
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: brain-task-app
  template:
    metadata:
      labels:
        app: brain-task-app
    spec:
      containers:
        - name: brain-task-app
          image: 866945988845.dkr.ecr.us-east-1.amazonaws.com/brain-task-app:latest
          ports:
            - containerPort: 80
